name = "LunarFox"
author = "OrzMiku"
version = "1.1.0+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfe0464c8512fb366ee9e5b72c7d2b1c343ba1843ba3becac7cf37096452d1f3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
