name = "LunarFox"
author = "OrzMiku"
version = "1.1.0+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aff788406f5275dd596eeccbcd12a16576cc0f16f6e9c7759824f5ff63ab7f87"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
