name = "LunarFox"
author = "OrzMiku"
version = "1.0.7+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd14070206f3d0b9728de17a254658c41bb1f30a278cafbb2aa44b278c320763"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
