name = "LunarFox"
author = "OrzMiku"
version = "1.0.2.hotfix+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbd15ab410bd6a3f7896a25573acad719be31e410893a45cc93aa566179fd3e9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
