name = "LunarFox"
author = "OrzMiku"
version = "1.0.5+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e270b62de2447754c2afc851e664a448c00022242b9d9d533159e7e43c1a26d0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
