name = "LunarFox"
author = "OrzMiku"
version = "1.0.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77bff0dfd7cc6438339576463e18ee3445f5e32204835057d70dd0bc3f975d10"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
