name = "LunarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1083e17ed07bec678e19e4638096c0d4ab23cbadd6bcedbd59cc0f8849ed8d6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
