name = "LunarFox Fabric"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b27d6e6ac22d672ee943eda17adba524cc131a34226664db4beb32b09909c104"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
