name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "670fb3003a5baef6f4e8774e93d693baa84c40d3fcb13eeb2005116cb2d5c42d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
