name = "LunarFox"
author = "OrzMiku"
version = "1.0.2.hotfix+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1395a00656ff08cdffcf5103f3f22d3a179d4530d4747f70b9d6a768067c4736"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
