name = "LunarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88dc27786864d27d214b9b2c7527a94b8b102267ee6fcb46e56a08ad189b910a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
