name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78e9f78822b573f794aca5acf973347b406a56ff433be7d3a2bdfcdf00fd03cf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
