name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bbbcaedce658964005a9bebcdfdb6d0b05bc138e5f401c927bba82bf4eb3e5e"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
