name = "LunarFox"
author = "OrzMiku"
version = "1.0.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84de9435a263d088ec83d1bc0950d8cbb7c720115f83a7b3c6d45e42a6af79f5"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
