name = "LunarFox"
author = "OrzMiku"
version = "1.0.9+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8b8d3a308217acf02100f10a6913529ea6ee80192dccac3c29c3a83307899d2"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
