name = "LunarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19916135652ccf192b321b32e023bfdcc7944819d0dc51e2674bdac4e52b0364"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
