name = "LunarFox"
author = "OrzMiku"
version = "1.0.6+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d75361f999fdb1d9fa12b40a99daa5c2bc24d98b06727e79db581fc2857ddbf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
