name = "LunarFox"
author = "OrzMiku"
version = "1.0.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b22483226ebf3a8e3f2ae0b1fa7a8292e2ea8df236dd871d0d07b8b456131d43"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
