name = "LunarFox"
author = "OrzMiku"
version = "1.0.2.hotfix+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96ff5a4d21e7350014fdea2a2114a6a2f228e8a688eb6884cdccc4b01b5263a0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
