name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a2+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e22f0ad5371d67e8d90c0df9edb77878729d50a18800cb5228698f0a861afb7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
