name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a2+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b415be5e38b8ce03330452b3be160df9190e9b932aab35877bc4bb196f24a09"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
