name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "048707cabe4ac0e4f4a4514a641b290a1ec43a10c6b8f5733f47c5373faf35a7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
