name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23eebea0792212737acb1cf2e923766a532b8c99135d3f3edc0df46c6320e354"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
