name = "LunarFox"
author = "OrzMiku"
version = "1.1.0-beta.1+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b42cd1c1c973dce0f7886d4aa3871cb48c640a27cb86bc0f835e6bdfbc2a1be"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
