name = "LunarFox"
author = "OrzMiku"
version = "1.1.0+mc1.21.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da9f34431d1fbdf3076bf4371b35172006df533ec161b19826e77ec099e512d0"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
