name = "LunarFox"
author = "OrzMiku"
version = "1.0.7+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5d0d850fd9c93ef1d6ea4a23f5cc9e37bce5ffbc4efcf3e51e2adbaa0aeced3"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
