name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ccf3abb34d38071e3e6017fea063bd28468d21c3818b99de3dbdc042fc76162"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
