name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe08b9e37a1a11ee4cfd289c1b8c9cf877df9655a1e1a38212e70f0c52e30ce"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
