name = "LunarFox"
author = "OrzMiku"
version = "1.0.9-alpha.1+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90b3a26bf5b755fda07100a9a1cc5282a85f47ebd0a4331fa12a33ab42e81093"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
