name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ec55217da6a50c82fc6c89ced3f9a097952671377b53d2a4fb4cda92da427d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
