name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a2+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1748d30f68af5b3adafcb14436df9d347af014ab30cbc21df1d5d063628dc19"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
