name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adcf0d774f2d35e0345b6bfb5232bf986c8cf5f12a9baa5396f8e08b31455371"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
