name = "LunarFox"
author = "OrzMiku"
version = "1.0.6.a3+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74fbbaa4885ea04b58d3a387bcb45d8c5d89014064f4ce178688357515079d41"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
