name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be41e4bf25bff5ae187d039ce9d9ad05367a22a3741ff17ad99dedf0eda657d5"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
