name = "LunarFox"
author = "OrzMiku"
version = "1.0.9-alpha.1+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a177dd99173e7d3cce754f29da2570c914fdd8391b503f074ac11b71e3067e70"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
