name = "LunarFox"
author = "OrzMiku"
version = "1.0.6.a2+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d4f25ae2e0ae40e0f4159dda8fe39f912761d657d8403d67eecd8e4c28573f3"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
