name = "LunarFox"
author = "OrzMiku"
version = "1.0.5.a1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6637ab393c21a183d5345fe7dfbd3c132740639db33887cda36b2a7aad3fefb"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
