name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d645f8b3157744d5eec67a698de272cd9c8b6d8d93e365ae0915c47f9d4ee9d1"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
