name = "LunarFox"
author = "OrzMiku"
version = "1.0.9-alpha.1+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "081772532600d3f7b5f78630ae44e800048eaff8f772e1756cddb4f175781565"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
