name = "LunarFox"
author = "OrzMiku"
version = "1.0.6.a3+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ceeee3772e3969d83979b183b236a4e90addd7c1e7ad2f292cc31f7845bc4ed"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
