name = "LunarFox"
author = "OrzMiku"
version = "1.0.9-alpha.1+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a3522b973ae1d68b10c58a36d03837484f4cee8f530abf211495aa862b3ec9c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
