name = "LunarFox"
author = "OrzMiku"
version = "1.0.6.a3+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64f2de48b69288107b89210e6ffcbfc155804530cc8bb56c93553beaf85e3f60"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
