name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deb435188db8bc70519742e9d9804ad618b6aac53abd0dfdb68f49fc9fdf5d5e"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
