name = "LunarFox"
author = "OrzMiku"
version = "1.0.9+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "306022adf3fb517cbb709e1e2c29415919e11993d3ee6efc54cc3068aeeea39c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
