name = "LunarFox"
author = "OrzMiku"
version = "1.0.2.hotfix+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3940eb49f9b31e7329ceae28503451d4b3ffe88015e9fcf9b35f7a37fcb7340"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
