name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb28a3d5571a16243e063834dbbc1be0f68a8843888b4f5e8a2018984232edc"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
