name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34c013e41e77b90671bf11a2a6451e4a9906e05a2aabea50e3c1d84f0425b897"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
