name = "LunarFox"
author = "OrzMiku"
version = "1.0.5+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "707ef2eceb399eb49f611b2863056dddf005197f06bbd712d5a3083177e467f2"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
