name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52bfd6ee6075250e096b79804613ce20be1e7213487a52e4e79a987f705b0194"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
