name = "LunarFox"
author = "OrzMiku"
version = "1.0.7+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "723f6271386fe1be14b235b6027ead1d039ff8223e0ecc2cd84d07e4a0b74204"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
