name = "LunarFox"
author = "OrzMiku"
version = "1.0.9+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9246d73cdffb579bea5ced31361463929ba5ecc4c8a33c84d0f2d078aa78e0b1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
