name = "LunarFox"
author = "OrzMiku"
version = "1.0.6+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b25277c5cf92bd95e00038de8c11d56b81789de6c60ea4d49e99358297ce2e5d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
