name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec08691a3016ff12cb3a607d95f17bb4d7203c862d3c9abd97afa46a936040bf"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
