name = "LunarFox"
author = "OrzMiku"
version = "1.0.4+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ac5c1e9dadf71a193d599197090c88677bc213dabb375ffed23284f98609874"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
