name = "LunarFox"
author = "OrzMiku"
version = "1.0.6+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8755f24a0f811ffc1d693d1ad0be908ca4b1b93fbc10a11b01ce7f5102c8627f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
