name = "LunarFox"
author = "OrzMiku"
version = "1.0.7+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17169c6adb9776a9a6dcf55dce916ab5d26a8c6b7eed09cea6f805a42f043ec3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
