name = "LunarFox"
author = "OrzMiku"
version = "1.0.9+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a574063a3f7bf4ca3ab92834c5fe2ea87d09b6f54925c4cb81c52e8ec6a8f919"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
