name = "LunarFox"
author = "OrzMiku"
version = "1.0.2.hotfix+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd89afbb491ae3318399f3ea99f9afaa1f607217eebd00ae6ae061b13563eda6"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
