name = "LunarFox"
author = "OrzMiku"
version = "1.0.6+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfff90dac22e932120aef883bd0e10ddab096f835da5cb080381cd820e670601"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
