name = "LunarFox"
author = "OrzMiku"
version = "1.0.5+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "150581c18ad61ffc55351f2ad723ee8e0d2d969831df57064c195865869971d3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
