name = "LunarFox"
author = "OrzMiku"
version = "1.0.6+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7ccab1ed832866545bb6dabdbcbad4c68b055082c1687581de1c7248e26123f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
