name = "LunarFox"
author = "OrzMiku"
version = "1.0.8+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3058a18305701d1cc2f02577d0051edba3f7e18c62ae47c1ef688e4aaa37c315"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
