name = "LunarFox"
author = "OrzMiku"
version = "1.1.0+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32b56b4c35f1690a58a10598fa54d109016c2a7ffa85c875fa7245814e0d8e0b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
