name = "LunarFox"
author = "OrzMiku"
version = "1.1.0+mc1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae34ad19f7f84f91176a303e8eb5f4658a24d165c73887773cfd5b6f3af1fbcc"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
