name: Export Modpack
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual export'
        required: false
        default: 'Manual modpack export'

jobs:
  export-modpack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Export and Upload Modpacks
      run: |
        for dir in $(find versions -type d); do
          cd "$dir"
          packwiz modrinth export
          modpack_name=$(ls *.mrpack | sed "s/\.mrpack$//")
          commit_hash=$(git rev-parse --short HEAD)
          echo "MODPACK_NAME=$modpack_name" >> $GITHUB_ENV
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV
          cd - > /dev/null
        done
    
    - name: Upload Modpacks
      uses: actions/upload-artifact@v3
      with:
        name: "${{ env.COMMIT_HASH }}_${{ env.MODPACK_NAME }}"
        path: "./${{ env.MODPACK_NAME }}.mrpack"
        retention-days: 7