name: Export Modpack
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual export'
        required: false
        default: 'Manual modpack export'

jobs:
  export-modpack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Export Modpacks
      run: |
        for version in versions/*/*; do
          cd "$version"
          packwiz modrinth export
          modpack_name=$(ls *.mrpack | sed 's/.mrpack$//')
          commit_hash=$(git rev-parse --short HEAD)
          echo "Uploading modpack: $modpack_name"
          cd ..
        done
    
    - name: Upload Modpacks
      run: |
        for version in versions/*/*; do
          cd "$version"
          modpack_name=$(ls *.mrpack | sed 's/.mrpack$//')
          commit_hash=$(git rev-parse --short HEAD)
          upload_name="${commit_hash}_${modpack_name}"
          echo "Uploading ${upload_name}.mrpack"
          actions/upload-artifact@v4 -name "${upload_name}" -path "./${modpack_name}.mrpack" -retention-days 7
          cd ..
        done