name: Export Modpack
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual export'
        required: false
        default: 'Manual modpack export'

jobs:
  export-modpack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest
    
    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Get current commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Export Modrinth Modpack (fabric_1.21.1)
      run: |
        cd
        cd versions/fabric/1.21.1
        packwiz modrinth export
        echo "MODPACK_NAME=$(ls *.mrpack | sed 's/.mrpack$//')" >> $GITHUB_ENV
    
    - name: Upload Modpack (fabric_1.21.1)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.COMMIT_HASH }}_${{ env.MODPACK_NAME }}
        path: versions/fabric/1.21.1/${{ env.MODPACK_NAME }}.mrpack
        retention-days: 7

    - name: Export Modrinth Modpack (fabric_1.20.1)
      run: |
        cd
        cd versions/fabric/1.20.1
        packwiz modrinth export
        echo "MODPACK_NAME=$(ls *.mrpack | sed 's/.mrpack$//')" >> $GITHUB_ENV
    
    - name: Upload Modpack (fabric_1.20.1)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.COMMIT_HASH }}_${{ env.MODPACK_NAME }}
        path: versions/fabric/1.21.1/${{ env.MODPACK_NAME }}.mrpack
        retention-days: 7